### PR TITLE
Created Json and wired to each emotion response range

### PR DESCRIPTION
**Pull request by dvillasmil08**
Please review any merge conflicts.

### CODE REVIEW

**Comment by dvillasmil08** [comment]
Please ensure merge is to dev and not master

**Comment by Nfada2010** [comment]
no merge conflicts

**Review by ja-br — APPROVED** [review]
Guess it’s ok

**Comment by dvillasmil08** [comment]
Review changes

**Review by amart21 — APPROVED** [review]

**Review by Nfada2010 — APPROVED** [review]

**Pull request merged**
